# cows and bulls --->>> fun
# The game works like this:

# Randomly generate a 4-digit number. -->>> fun
# Ask the user to guess a 4-digit number. fun
# For every digit that the user guessed correctly in the correct place, they have a “cow”. -->> fun1
# For every digit the user guessed correctly in the wrong place is a “bull.” -->> fun1
#
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. fun
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.
import random


def cows_and_bulls():

    # Generating random number
    print("Welcome to the Cows and Bulls Game!")
    randnum = "".join([str(random.randint(0, 9)) for _ in range(4)])

    # Cow counter function
    def cow_counter(randnum, user_guess):
        cow_num = 0
        randnum_index = 0

        for num in randnum:
            randnum_index += 1
            user_guess_index = 0
            for num1 in user_guess:
                user_guess_index += 1
                if num1 == num and randnum_index == user_guess_index:
                    cow_num += 1
        return cow_num

    # bull counter function
    def bull_counter(randnum, user_guess):
        bull_num = 0
        randnum_index = 0

        for num in randnum:
            randnum_index += 1
            user_guess_index = 0
            for num1 in user_guess:
                user_guess_index += 1
                if num1 == num and randnum_index != user_guess_index:
                    bull_num += 1
        return bull_num

    guesses = 0
    while True:
        user_guess = input("Enter a number:\nQUIT: Q\n")
        guesses += 1
        cows = cow_counter(randnum, user_guess)
        bulls = bull_counter(randnum, user_guess)

        if cows == 4:
            print(
                f"Comgrats! We have a WINNER!!!\nNumber of Guesses: {guesses}")
            opt = input("Play again:(Y/N)")
            if opt.lower() == "y":
                pass
            elif opt.lower() == "n":
                break

        elif user_guess.lower() == "q":
            print(f"HARD LUCK LOOSER. Number was {randnum}")
            opt = input("Play again:(Y/N)")
            if opt.lower() == "y":
                pass
            elif opt.lower() == "n":
                break
        else:
            print(
                f"Cows: {cows}\nBulls: {bulls}")


cows_and_bulls()
